server.port=8080
server.error.include-message=always
server.compression.enabled=true
server.compression.min-response-size=1024

spring.mvc.format.date=iso
spring.mvc.format.date-time=iso
spring.web.resources.cache.period=3600

logging.level.com.pushkar.netflix=INFO